# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["ci_preview"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          # version: 10
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          # cache-dependency-path: subdir/package-lock.json
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - run: pnpm install
      - run: pnpm wiki:build

      - name: Deploy wiki to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }} # 在GitHub仓库的Settings -> Secrets中设置你的SSH密钥
          ARGS: "-rltgoDzvO --delete" # rsync参数，用于同步文件并删除目标服务器上不存在的文件
          SOURCE: "wiki/.vuepress/dist/" # 要上传的目录，这里是构建后的dist目录
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }} # 你的服务器IP或域名
          REMOTE_USER: ${{ secrets.REMOTE_USER }} # 服务器上的用户名，通常是ubuntu或root等
          TARGET: ${{ secrets.REMOTE_TARGET_FOR_WIKI }} # 在服务器上的目标目录路径，例如 /var/www/html/myproject/dist/
